AUGMENTATION : True
IMAGE_SIZE : [224, 224, 3] #as per VGG 16 model
BATCH_SIZE : 16
INCLUDE_TOP : False
EPOCHS : 1  #15 for version2 and 30 for version1
CLASSES : 2
WEIGHTS : imagenet
LEARNING_RATE : 0.01 # 0.02 for version2 and 0.01 for version1 